title: seattle.rs
email: trey@seattle.rs
description: >
  Seattle's Rust meetup group, seattle.rs. We have talks about learning
  and using Rust in today's industry.
baseurl: ""
url: "http://seattle.rs"
twitter_username: seattlers
github_username:  seattlers

# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
collections:
  - meetups

timezone: America/Los_Angeles
